name: Build PHP WASM for Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3 curl git autoconf bison re2c libxml2-dev libsqlite3-dev libcurl4-openssl-dev pkg-config

      - name: Set up Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK_ENV=$(pwd)/emsdk/emsdk_env.sh" >> $GITHUB_ENV

      - name: Configure PHP build
        run: |
          source "$EMSDK_ENV"
          ./buildconf --force
          emconfigure ./configure \
            --disable-all \
            --disable-cli \
            --without-pear \
            --enable-session \
            --enable-mbstring \
            --with-curl \
            --without-libxml

      - name: Compile PHP to WASM
        run: |
          source "$EMSDK_ENV"
          emmake make -j$(nproc)

      - name: Bundle output into worker.js
        run: |
          mkdir -p dist
          base64 sapi/cgi/php.wasm > dist/php.wasm.base64
          sed "s|{{BASE64_WASM}}|$(cat dist/php.wasm.base64)|" templates/worker.template.js > dist/worker.js
