name: Build PHP WASM for Cloudflare Workers

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build libxml2 with Emscripten
        run: |
          source ./emsdk/emsdk_env.sh
          git clone https://gitlab.gnome.org/GNOME/libxml2.git
          cd libxml2
          emconfigure ./autogen.sh \
            --host=wasm32-unknown-emscripten \
            --without-python \
            --without-zlib \
            --disable-shared \
            --enable-static \
            --prefix=$(pwd)/build
          emmake make -j$(nproc)
          emmake make install
          cd ..

      - name: Build on
