name: Build PHP WASM for Cloudflare Workers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # 注意：这里不做 sudo 安装依赖，依赖需要提前预装
      # 如果你自建 runner 已经预装依赖，可以注释掉下面安装步骤
      # - name: Install dependencies on self-hosted runner
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y cmake ninja-build build-essential autoconf bison re2c libtool pkg-config git curl

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - name: Disable OPCache in source
        run: |
          # 注释 ext/opcache/config.m4 中启用 opcache 的宏，避免 configure 识别参数报错
          sed -i '/PHP_ARG_ENABLE(opcache/,/^$/ s/^/#/' ext/opcache/config.m4

      - name: Regenerate build configuration
        run: |
          source emsdk/emsdk_env.sh
          ./buildconf --force

      - name: Configure PHP for Emscripten WASM build
        run: |
          source emsdk/emsdk_env.sh
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --without-libxml

      - name: Build PHP WASM
        run: |
          source emsdk/emsdk_env.sh
          emmake make -j$(nproc)
