name: Build and Deploy PHP-WASM Worker

on:
  push:
    branches:
      - main   # 你要监控的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 Emscripten SDK 环境
      - name: Install Emscripten SDK
        uses: emscripten-core/setup-emsdk@v2
        with:
          emsdk-version: latest

      # 编译 PHP 源码（假设入口文件 src/php.c，改为你的真实入口）
      - name: Build PHP WASM with Emscripten
        run: |
          emcc src/php.c \
            -o dist/php-wasm.js \
            -s WASM=1 \
            -s MODULARIZE=1 \
            -s EXPORT_NAME='createPHPModule' \
            -O3 \
            --closure 1
          
          # 这里可改为你真正的构建命令和参数

      # 安装 wrangler（Cloudflare CLI）
      - name: Install Wrangler
        run: npm install -g wrangler@4.26.1

      # 登录 Cloudflare（你需要把 CF_API_TOKEN 放到仓库 Secrets）
      - name: Authenticate Wrangler
        run: wrangler login

      # 发布到 Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
