name: Build PHP WASM for Cloudflare Workers

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK=$PWD" >> $GITHUB_ENV
          echo "EMSCRIPTEN=$PWD/upstream/emscripten" >> $GITHUB_ENV
          echo "$PWD:$PWD/upstream/emscripten" >> $GITHUB_PATH

      - name: Set environment variables for Emscripten
        run: |
          echo "PATH=$EMSDK:$EMSCRIPTEN:$PATH" >> $GITHUB_ENV
          echo "EMSDK_NODE=$EMSDK/node/22.16.0_64bit/bin/node" >> $GITHUB_ENV
          echo "EM_CONFIG=$EMSDK/.emscripten" >> $GITHUB_ENV
          echo "EM_CACHE=$EMSDK/.emscripten_cache" >> $GITHUB_ENV

      - name: Clone libxml2 (if not exists)
        run: |
          if [ ! -d "libxml2" ]; then
            git clone https://github.com/GNOME/libxml2.git
          fi

      - name: Configure libxml2
        run: |
          cd libxml2
          if [ ! -f "Makefile" ]; then
            ./autogen.sh --without-zlib
          fi

      - name: Build libxml2 with emconfigure/emmake
        run: |
          cd libxml2
          emconfigure ./configure --without-zlib
          emmake make -j$(nproc)

      - name: Build PHP
        run: |
          ./buildconf --force
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --disable-opcache \
            --without-libxml
          emmake make -j$(nproc)

      - name: Post-build steps
        run: |
          echo "Build complete"
