name: Build and Deploy PHP WASM Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 支持手动触发，便于调试

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison re2c libxml2-dev libsqlite3-dev libzip-dev libssl-dev unzip pkg-config

      - name: Setup PHP build
        run: |
          ./buildconf
          emconfigure ./configure --disable-all --enable-cli
          emmake make -j$(nproc)

      - name: Copy wasm output
        run: |
          mkdir -p dist
          cp sapi/cli/php dist/php.wasm

      - name: Install Wrangler
        run: npm install -g wrangler@4.26.1

      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN
