name: Build PHP WASM with mbstring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PHP repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake bison re2c autoconf automake libtool pkg-config wget tar

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..

      - name: Clone and Build Oniguruma for Emscripten
        run: |
          source emsdk/emsdk_env.sh
          git clone https://github.com/kkos/oniguruma.git
          cd oniguruma
          emcmake cmake -Bbuild
          emmake make -C build
          echo "ONIG_CFLAGS=-I$(pwd)/src" >> $GITHUB_ENV
          echo "ONIG_LIBS=$(pwd)/build/libonig.a" >> $GITHUB_ENV
          cd ..

      - name: Disable OPCache in PHP source
        run: |
          mv ext/opcache/config.m4 ext/opcache/config.m4.bak
          touch ext/opcache/config.m4

      - name: Clean previous build and regenerate configuration
        run: |
          cd $GITHUB_WORKSPACE   # 或 cd 到你的源码根目录
          source emsdk/emsdk_env.sh
          make distclean || true
          ./buildconf --force
          ls -l  # 检查有 configure 文件

      - name: Configure PHP for Emscripten WASM build
        run: |
          cd $GITHUB_WORKSPACE   # 确保在源码根目录
          source emsdk/emsdk_env.sh
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --enable-mbstring \
            --enable-session \
            --enable-filter \
            --enable-tokenizer \
            --without-libxml \
            --disable-pcre-jit

      - name: Build Optimized PHP WASM
        run: |
          source emsdk/emsdk_env.sh
          emmake make -j$(nproc) CFLAGS="-O3"

      - name: Strip debug symbols for smaller WASM
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
          tar xzf wabt-1.0.33-ubuntu.tar.gz
          ./wabt-1.0.33/bin/wasm-strip sapi/embed/php.wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php.wasm
          path: sapi/embed/php.wasm
