name: Build PHP WASM for Cloudflare Workers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies on self-hosted runner
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential autoconf bison re2c libtool pkg-config git curl

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - name: Regenerate build configuration
        run: |
          source emsdk/emsdk_env.sh
          ./buildconf --force

      - name: Configure PHP for Emscripten WASM build
        run: |
          source emsdk/emsdk_env.sh
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --disable-opcache \
            --disable-zend-opcache \
            --without-opcache \
            --disable-jit \
            --without-libxml

      - name: Build PHP WASM
        run: |
          source emsdk/emsdk_env.sh
          emmake make -j$(nproc)
