name: Build PHP WASM with mbstring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout PHP repository
        uses: actions/checkout@v4

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..

      - name: Clone and Build Oniguruma for Emscripten
        run: |
          source emsdk/emsdk_env.sh
          git clone https://github.com/kkos/oniguruma.git
          cd oniguruma
          emcmake cmake -Bbuild
          emmake make -C build
          echo "ONIG_CFLAGS=-I$(pwd)/src" >> $GITHUB_ENV
          echo "ONIG_LIBS=$(pwd)/build/libonig.a" >> $GITHUB_ENV
          cd ..

      - name: Patch ext/pcre/config.m4 for static build
        run: |
          cd $GITHUB_WORKSPACE
          rm -f configure aclocal.m4 libtool main/php_config.h.in config.status config.cache config.nice
          find . -name 'Makefile' -delete
          find . -name 'Makefile.in' -delete
          make distclean || true
          ./buildconf --force

      - name: Configure PHP for Emscripten WASM build (with static PCRE)
        run: |
          cd $GITHUB_WORKSPACE   # 确保在源码根目录
          source emsdk/emsdk_env.sh
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --enable-pcre=static \
            --enable-mbstring \
            --enable-session \
            --enable-filter \
            --enable-tokenizer \
            --without-libxml \
            --disable-opcache \
            PKG_CONFIG_PATH=/dev/null \
            ONIG_CFLAGS="$ONIG_CFLAGS" \
            ONIG_LIBS="$ONIG_LIBS" > configure.log 2>&1
          cat configure.log
      - name: Build Optimized PHP WASM
        run: |
          source emsdk/emsdk_env.sh
          emmake make -j$(nproc) CFLAGS="-O3" V=1 > make.log 2>&1 || true
      - name: Upload build logs (always run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            configure.log
            make.log
      - name: Strip debug symbols for smaller WASM
        if: success()  # 只有make成功才Strip
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
          tar xzf wabt-1.0.33-ubuntu.tar.gz
          ./wabt-1.0.33/bin/wasm-strip sapi/embed/php.wasm
      - name: Upload php.wasm
        if: success()  # 只有make成功才上传wasm
        uses: actions/upload-artifact@v4
        with:
          name: php.wasm
          path: sapi/embed/php.wasm
