name: Build PHP WASM with mbstring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout PHP repository
        uses: actions/checkout@v4

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
      - name: Clone and Build Oniguruma for Emscripten
        run: |
          source emsdk/emsdk_env.sh
          git clone https://github.com/kkos/oniguruma.git
          cd oniguruma
          emcmake cmake -Bbuild
          emmake make -C build
          echo "ONIG_CFLAGS=-I$(pwd)/src" >> $GITHUB_ENV
          echo "ONIG_LIBS=$(pwd)/build/libonig.a" >> $GITHUB_ENV
          cd ..
      - name: Disable OPCache in PHP source
        run: |
          mv ext/opcache/config0.m4 ext/opcache/config0.m4.bak
          touch ext/opcache/config0.m4
      - name: Clean previous build and regenerate configuration
        run: |
          cd $GITHUB_WORKSPACE   # 或 cd 到你的源码根目录
          source emsdk/emsdk_env.sh
          make distclean || true
          make clean || true
          ./buildconf --force
          ls -l configure # 检查有 configure 文件
      - name: Remove PCRE2 JIT source files
        run: |
          # Remove JIT source files to prevent them from being compiled
          rm -f ext/pcre/pcre2lib/pcre2_jit_compile.c
          rm -rf ext/pcre/pcre2lib/sljit

          # Patch ext/pcre/config0.m4 to force built-in static compilation
          sed -i '/PHP_NEW_EXTENSION(pcre/,/)/s/,$/, yes/' ext/pcre/config0.m4

          sed -i 's/,$/, yes/' ext/pcre/config0.m4

          # Disable PCRE JIT in php_pcre.c to avoid runtime dependency
          echo '#undef HAVE_PCRE_JIT_SUPPORT' >> ext/pcre/php_pcre.c
          echo '#define PCRE2_DISABLE_JIT 1' >> ext/pcre/php_pcre.c
      - name: Configure PHP for Emscripten WASM build
        run: |
          cd $GITHUB_WORKSPACE   # 确保在源码根目录
          source emsdk/emsdk_env.sh
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --enable-embed=static \
            --enable-pcre \
            --enable-mbstring \
            --enable-session \
            --enable-filter \
            --enable-tokenizer \
            --without-libxml > configure.log 2>&1
          cat configure.log
      - name: Build Optimized PHP WASM
        run: |
          source emsdk/emsdk_env.sh
          emmake make -j$(nproc) CFLAGS="-O3" V=1 > make.log 2>&1 || true
      - name: Upload build logs (always run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            configure.log
            make.log
      - name: Strip debug symbols for smaller WASM
        if: success()  # 只有make成功才Strip
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
          tar xzf wabt-1.0.33-ubuntu.tar.gz
          ./wabt-1.0.33/bin/wasm-strip sapi/embed/php.wasm
      - name: Upload php.wasm
        if: success()  # 只有make成功才上传wasm
        uses: actions/upload-artifact@v4
        with:
          name: php.wasm
          path: sapi/embed/php.wasm
