      - name: Build oniguruma with Emscripten
        run: |
          source ./emsdk/emsdk_env.sh
          git clone https://github.com/kkos/oniguruma.git
          cd oniguruma
          autoreconf -vfi
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-shared \
            --disable-dependency-tracking \
            --prefix=$(pwd)/build

          emmake make -j$(nproc)
          emmake make install
          cd ..

      - name: Clean previous builds
        run: |
          git clean -xfd || true
          rm -f config.cache autom4te.cache || true
          
      - name: Generate configure script if needed
        run: |
          if [ ! -x configure ]; then ./buildconf --force; fi

      - name: Configure PHP with Emscripten
        env:
          LIBXML_CFLAGS: "-I$GITHUB_WORKSPACE/libxml2/build/include"
          LIBXML_LIBS: "-L$GITHUB_WORKSPACE/libxml2/build/lib -lxml2"
          ONIG_CFLAGS: "-I$GITHUB_WORKSPACE/oniguruma/build/include"
          ONIG_LIBS: "$GITHUB_WORKSPACE/oniguruma/build/lib/libonig.a"
          CFLAGS: "-O2 -sALLOW_MEMORY_GROWTH=1 -sENVIRONMENT=web,worker -sEXPORTED_FUNCTIONS=[_main,_php_embed_init,_php_embed_shutdown] -sEXPORTED_RUNTIME_METHODS=[cwrap,ccall]"
        run: |
          source ./emsdk/emsdk_env.sh
          export CC=emcc
          export CXX=em++
          emconfigure ./configure \
            --host=wasm32-unknown-emscripten \
            --disable-all \
            --disable-cli \
            --disable-cgi \
            --disable-phpdbg \
            --disable-zlib \
            --disable-curl \
            --without-pear \
            --with-libxml \
            --enable-embed=static \
            --enable-simplexml \
            --enable-xml \
            --enable-session \
            --enable-mbstring \
            --enable-json \
            --enable-tokenizer \
            --enable-filter \
            --enable-posix \
            LIBXML_CFLAGS="$LIBXML_CFLAGS" \
            LIBXML_LIBS="$LIBXML_LIBS" \
            ONIG_CFLAGS="$ONIG_CFLAGS" \
            ONIG_LIBS="$ONIG_LIBS" \
            --cache-file=config.cache

      - name: Show config.log if configure fails
        if: failure()
        run: |
          echo "configure failed, showing config.log:"
          find . -name config.log -exec cat {} \;

      - name: Compile PHP to WASM
        run: |
          source ./emsdk/emsdk_env.sh
          emmake make -j$(nproc) > build.log 2>&1 || (cat build.log && false)

      - name: Package output into worker.js
        run: |
          mkdir -p dist
          WASM_FILE=$(find sapi -name '*.wasm' | head -n1)
          if [ ! -f "$WASM_FILE" ]; then echo "No .wasm file found!" && exit 1; fi
          base64 "$WASM_FILE" > dist/php.wasm.base64
          WASM_BASE64_CONTENT=$(cat dist/php.wasm.base64)
          cat > dist/worker.js <<EOF
          const wasmBase64 = \`${WASM_BASE64_CONTENT}\`;
          addEventListener('fetch', event => {
          event.respondWith(new Response('PHP WASM Ready'));
          });
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasmphp
          path: dist/
