name: Build PHP WASM

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y autoconf bison re2c libxml2-dev \
            libsqlite3-dev libzip-dev libssl-dev unzip pkg-config git

      - name: Clone php-src with submodules
        run: |
          git clone --recursive https://github.com/php/php-src.git php-src
          cd php-src
          ./buildconf || true

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure PHP with Emscripten
        working-directory: ./php-src
        run: |
          emconfigure ./configure --disable-all --enable-cli

      - name: Build PHP with emmake
        working-directory: ./php-src
        run: |
          emmake make -j$(nproc)

      - name: Save PHP WASM output
        run: |
          mkdir -p dist
          cp php-src/sapi/cli/php dist/php.wasm
