name: Build PHP to WebAssembly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v2
        with:
          emsdk-version: latest

      - name: Prepare PHP build
        run: |
          ./buildconf
          emconfigure ./configure --disable-all --enable-cli
          emmake make -j$(nproc)

      - name: Copy php.wasm
        run: |
          mkdir -p dist
          cp sapi/cli/php dist/php.wasm

      - name: Install Wrangler
        run: npm install -g wrangler@4.26.1

      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish --api-token $CF_API_TOKEN
