name: Build and Deploy PHP WASM Worker

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build PHP WASM
        run: |
          mkdir -p dist
          emcc src/php.c \
            -o dist/php-wasm.js \
            -s WASM=1 \
            -s MODULARIZE=1 \
            -s EXPORT_NAME='createPHPModule' \
            -O3 \
            --closure 1

      - name: Install Wrangler
        run: npm install -g wrangler@4.26.1

      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish --api-token $CF_API_TOKEN
